---
# tasks file for docker
- name: Instalar Docker no "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  include_tasks: setting-docker-{{ ansible_distribution }}.yml
...
