---
# tasks file for docker
- name: Remover versões antigas do Docker
  yum: 
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-engine
    - docker-engine-selinux
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
  when:
    - ansible_distribution == "CentOS" 

- name: Instalar Dependencias
  yum: 
    name: "{{ item }}" 
    state: latest
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - curl
    
- name: Adicionando o repositorio do Docker CE
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    validate_certs: no
    
- name: Instalando Docker
  yum: 
    name: docker-ce 
    state: latest
  notify:
    - Start Docker  
...
