## SystemD
- name: "Start docker"
  systemd:
    state: started
    name: docker.service
    enabled: yes
    force: yes
  ignore_errors: yes
  when: ansible_service_mgr == "systemd"

- name: "Restart docker"
  systemd:
    state: restarted
    name: docker.service
    force: yes
  ignore_errors: yes
  when: ansible_service_mgr == "systemd"

## SystemV
- name: "Start docker"
  service:
    state: started
    name: docker
    enabled: yes
  when: ansible_service_mgr == "service"
    
- name: "Restart docker"
  service:
    state: restarted
    name: docker
  when: ansible_service_mgr == "service"